import { jsPDF } from "jspdf";

export type DownloadFormat = "png" | "svg" | "pdf";

interface DownloadOptions {
  value: string;
  fileName: string;
  fgColor: string;
  bgColor: string;
  size?: number;
}

export function useQRDownload() {
  const downloadPNG = async ({ value, fileName, fgColor, bgColor, size = 400 }: DownloadOptions) => {
    const canvas = document.createElement("canvas");
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    // Use dynamic import for QRCode generation
    const QRCode = await import("qrcode");
    
    await QRCode.toCanvas(canvas, value, {
      width: size,
      margin: 2,
      color: {
        dark: fgColor,
        light: bgColor,
      },
    });

    const link = document.createElement("a");
    link.download = `${fileName}.png`;
    link.href = canvas.toDataURL("image/png");
    link.click();
  };

  const downloadSVG = async ({ value, fileName, fgColor, bgColor }: DownloadOptions) => {
    const QRCode = await import("qrcode");
    
    const svgString = await QRCode.toString(value, {
      type: "svg",
      margin: 2,
      color: {
        dark: fgColor,
        light: bgColor,
      },
    });

    const blob = new Blob([svgString], { type: "image/svg+xml" });
    const link = document.createElement("a");
    link.download = `${fileName}.svg`;
    link.href = URL.createObjectURL(blob);
    link.click();
    URL.revokeObjectURL(link.href);
  };

  const downloadPDF = async ({ value, fileName, fgColor, bgColor, size = 400 }: DownloadOptions) => {
    const canvas = document.createElement("canvas");
    const QRCode = await import("qrcode");
    
    await QRCode.toCanvas(canvas, value, {
      width: size,
      margin: 2,
      color: {
        dark: fgColor,
        light: bgColor,
      },
    });

    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    const pdfWidth = pdf.internal.pageSize.getWidth();
    const qrSize = 80;
    const x = (pdfWidth - qrSize) / 2;
    const y = 40;

    pdf.setFontSize(20);
    pdf.text(fileName, pdfWidth / 2, 25, { align: "center" });
    pdf.addImage(imgData, "PNG", x, y, qrSize, qrSize);
    pdf.setFontSize(10);
    pdf.setTextColor(128);
    pdf.text("Generated by IEOSUIA QR", pdfWidth / 2, y + qrSize + 15, { align: "center" });
    
    pdf.save(`${fileName}.pdf`);
  };

  const download = async (format: DownloadFormat, options: DownloadOptions) => {
    switch (format) {
      case "png":
        await downloadPNG(options);
        break;
      case "svg":
        await downloadSVG(options);
        break;
      case "pdf":
        await downloadPDF(options);
        break;
    }
  };

  return { download, downloadPNG, downloadSVG, downloadPDF };
}
